"""add recipe_ingredients and ingredients tables

Revision ID: 0cb0b30c7a56
Revises: 
Create Date: 2023-03-06 14:33:44.332896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb0b30c7a56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructions',
    sa.Column('instruction_id', sa.Integer(), nullable=False),
    sa.Column('instruction_details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('instruction_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=True),
    sa.Column('total_cook_time', sa.String(), nullable=True),
    sa.Column('is_vegetarian', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructions_id'], ['instructions.instruction_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_table('instructions')
    # ### end Alembic commands ###
