"""deleting madison test entries

Revision ID: 27495fe9e7bc
Revises: 5ba0d76f6533
Create Date: 2023-03-09 07:21:58.531666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27495fe9e7bc'
down_revision = '5ba0d76f6533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
