"""removed instructions

Revision ID: 2bde124b840a
Revises: 3d6a66f61eee
Create Date: 2023-03-09 23:23:56.632170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bde124b840a'
down_revision = '3d6a66f61eee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
