"""added last name to User

Revision ID: 5ba0d76f6533
Revises: 4a81546eb6d7
Create Date: 2023-03-09 07:10:30.996102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba0d76f6533'
down_revision = '4a81546eb6d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
