"""working on instructions class

Revision ID: 970fddfea53c
Revises: 44d5b972563c
Create Date: 2023-03-09 20:45:30.645975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970fddfea53c'
down_revision = '44d5b972563c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructions',
    sa.Column('instruction_id', sa.Integer(), nullable=False),
    sa.Column('instruction_details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('instruction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructions')
    # ### end Alembic commands ###
